config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'searches#home'
  get '/result', to: 'searches#result'
  get '/solved', to: 'questions#solved'
  post 'favorite_review/:id', to: 'favorite_reviews#create', as: 'create_favorite_review'
  delete 'favorite_review/:id', to: 'favorite_reviews#destroy', as: 'destroy_favorite_review'
  resources :users, only: [:show, :edit, :update]
  resources :schools
  resources :reviews
  resources :questions
  resources :answers, only: [:create, :edit, :update, :destroy]
  resources :user_schools, only: [:destroy]
  resources :notifications, only: [:index, :destroy]
  delete '/notification_all', to: 'notifications#destroy_all', as: 'destroy_all_notification'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :school
  has_many :answers, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :name, presence: true, length: { maximum: 60 }
  validates :content, presence: true
  validates :user_id, presence: true

  def create_notification_answer!(current_user, answer_id)
    notification = current_user.active_notifications.new(
      question_id: id,
      answer_id: answer_id,
      visited_id: user_id,
      action: 'answer'
    )
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @params = params[:question_index_params]
    @school = School.find(params[:school_id])
    @questions = Question.where(school_id: @school.id).order(created_at: :desc)
  end

  def show
    if Question.exists?(params[:id])
      @params = params[:question_show_params]
      @question = Question.find(params[:id])
      @answers = Answer.where(question_id: @question.id)
      gon.answers = @answers
      @answer = Answer.new
    else
      flash[:failure] = "質問は削除されています"
      redirect_to root_path
    end
  end

  def new
    @params = params[:question_new_params]
    @school = School.find(params[:school_id])
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if current_user?(@question.user)
      if @question.save
        flash[:success] = "質問を投稿しました"
        redirect_to questions_path(school_id: @question.school_id,
                                   question_index_params: "question_create")
      else
        @school = School.find(params[:school_id])
        flash.now[:failure] = "質問を投稿できませんでした"
        render "new"
      end
    else
      flash[:failure] = "他のユーザーで質問は投稿できません"
      redirect_to new_question_path
    end
  end

  def edit
    @params = params[:question_edit_params]
    @question = Question.find(params[:id])
    unless current_user?(@question.user)
      redirect_to question_path(@question)
    end
  end

  def update
    @question = Question.find(params[:id])
    if current_user?(@question.user)
      if @question.update(question_params)
        flash[:success] = "質問を変更しました"
        redirect_to question_path(@question)
      else
        @question.school = School.find(params[:hidden_school_id])
        flash.now[:failure] = "質問を変更できませんでした"
        render "edit"
      end
    else
      flash[:failure] = "他のユーザーの質問は変更できません"
      redirect_to question_path(@question)
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question_shcool_id = @question.school_id
    if current_user?(@question.user)
      if @question.destroy
        flash[:success] = "質問を削除しました"
        redirect_to questions_path(school_id: @question_shcool_id)
      else
        flash.now[:failure] = "質問を削除できませんでした"
        render "show"
      end
    else
      flash[:failure] = "他のユーザーの質問は削除できません"
      redirect_to question_path(@question)
    end
  end

  def solved
    @question = Question.find(params[:question_id])
    if current_user?(@question.user)
      if (@question.solution == 2) && (@question.answers.count == 0)
        @question.solution = 0
        if @question.save
          flash[:success] = "未回答に変更しました"
          redirect_to questions_path(school_id: @question.school_id)
        else
          flash.now[:failure] = "変更できませんでした"
          render "show"
        end
      elsif @question.solution == 0 || @question.solution == 1
        @question.solution = 2
        if @question.save
          flash[:success] = "解決済みに変更しました"
          redirect_to questions_path(school_id: @question.school_id)
        else
          flash.now[:failure] = "変更できませんでした"
          render "show"
        end
      else
        @question.solution = 1
        if @question.save
          flash[:success] = "未解決に変更しました"
          redirect_to questions_path(school_id: @question.school_id)
        else
          flash.now[:failure] = "変更できませんでした"
          render "show"
        end
      end
    else
      flash[:failure] = "他のユーザーの質問は変更できません"
      redirect_to question_path(@question)
    end
  end

  private

  def question_params
    params.require(:question).permit(:name, :content, :user_id, :school_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def solve(question_solution)
    case question_solution
    when 0
      "未回答"
    when 1
      "未解決"
    when 2
      "解決済み"
    end
  end
end

app/views/questions/_question_edit_page_link.html.erb
<div class="page-link">
  <% if params == "school_index" %>
    <ul class="flex five-links">
      <li><%= link_to 'スクール一覧', schools_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問詳細', question_path(question) %></li>
      <li>＞</li>
      <li><%= link_to '質問編集', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params ==  "review_create" %>
    <ul class="flex five-links">
      <li><%= link_to '口コミ投稿', new_review_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問詳細', question_path(question) %></li>
      <li>＞</li>
      <li><%= link_to '質問編集', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "result" %>
    <ul class="flex five-links">
      <li><%= link_to '検索', result_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問詳細', question_path(question) %></li>
      <li>＞</li>
      <li><%= link_to '質問編集', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "question_create" %>
    <ul class="flex">
      <li><%= link_to '質問投稿', new_question_path %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問詳細', question_path(question) %></li>
      <li>＞</li>
      <li><%= link_to '質問編集', "#", class: "link-underline" %></li>
    </ul>
  <% else %>
    <ul class="flex">
      <li><%= link_to '口コミ一覧', school_path(question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: question.school_id) %></li>
      <li>＞</li>
      <li><%= link_to '質問詳細', question_path(question) %></li>
      <li>＞</li>
      <li><%= link_to '質問編集', "#", class: "link-underline" %></li>
    </ul>
  <% end %>
</div>

app/views/questions/_question_edit_question_box.html.erb
<div class="review-and-question-box">
  <div class="review-and-question-box-content">
    <h2>質問編集</h2>
    <%= form_with model: question, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="review-and-question-content-border">
        <ul class="flex question-form-user">
          <% if current_user.image.attached? %>
            <li><%= image_tag current_user.image.variant(resize: '40x40!'), class: "user-icon", alt: "ユーザーアイコン" %></li>
          <% else %>
            <li><%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %></li>
          <% end %>
          <li class="question-form-user-name"><%= question.user.name %></li>
        </ul>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="review-and-question-content-border">
        <ul class="flex question-form-school">
          <li class="review-and-question-label"><%= f.label :school_id, "スクール名" %><span class="badge">必須</span></li>
          <li><%= f.collection_select(:school_id, School.all, :id, :name, include_blank: '選択してください') %></li>
        </ul>
      </div>
      <div class="review-and-question-content-border">
        <ul>
          <li class="review-and-question-label"><%= f.label :name, "質問タイトル" %><span class="badge">必須</span></li>
          <li><%= f.text_field :name, placeholder: "質問のタイトルを入力してください" %></li>
        </ul>
      </div>
      <div class="question-form-content">
        <ul>
          <li class="review-and-question-label"><%= f.label :content, "質問内容" %><span class="badge">必須</span></li>
          <li><%= f.text_area :content, placeholder: "質問を入力してください", class: "resize10" %></li>
        </ul>
      </div>
      <%= hidden_field_tag :hidden_school_id, question.school.id %>
      <div class="review-and-question-button">
        <%= f.submit '変更する', class: "submit-button" %>
        <%= link_to "戻る", question_path(question), class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_question_index_page_link.html.erb
<div class="page-link">
  <% if params == "school_index" %>
    <ul class="flex">
      <li><%= link_to 'スクール一覧', schools_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params ==  "review_create" %>
    <ul class="flex">
      <li><%= link_to '口コミ投稿', new_review_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "result" %>
    <ul class="flex">
      <li><%= link_to 'HOME', root_path %></li>
      <li>＞</li>
      <li><%= link_to '検索', result_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "question_create" %>
    <ul class="flex">
      <li><%= link_to '質問投稿', new_question_path %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', "#", class: "link-underline" %></li>
    </ul>
  <% else %>
    <ul class="flex">
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', "#", class: "link-underline" %></li>
    </ul>
  <% end %>
</div>

app/views/questions/_question_index_question_box.html.erb
<ul class="question-box">
  <%= link_to question_path(question, question_show_params: params) do %>
    <li>
      <% if question.solution == 0 %>
        <div class="solution solution-red">
          未回答
        </div>
      <% elsif question.solution == 1 %>
        <div class="solution solution-orange">
          未解決
        </div>
      <% else %>
        <div class="solution solution-green">
          解決済み
        </div>
      <% end %>
    </li>
    <li class="question-name hover-underline"><%= question.name %></li>
    <div class="flex">
      <li>
        <% if question.user.image.attached? %>
          <%= image_tag question.user.image.variant(resize: '35x35!'), class: "user-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      </li>
      <li class="question-user-name"><%= question.user.name %></li>
      <li class="question-time"><%= question.created_at.to_s(:datetime_jp) %></li>
    </div>
  <% end %>
</ul>

app/views/questions/_question_new_page_link.html.erb
<div class="page-link">
  <% if params == "school_index" %>
    <ul class="flex">
      <li><%= link_to 'スクール一覧', schools_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: school.id) %></li>
      <li>＞</li>
      <li><%= link_to '質問投稿', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params ==  "review_create" %>
    <ul class="flex">
      <li><%= link_to '口コミ投稿', new_review_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: school.id) %></li>
      <li>＞</li>
      <li><%= link_to '質問投稿', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "result" %>
    <ul class="flex">
      <li><%= link_to '検索', result_path %></li>
      <li>＞</li>
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: school.id) %></li>
      <li>＞</li>
      <li><%= link_to '質問投稿', "#", class: "link-underline" %></li>
    </ul>
  <% elsif params == "question_create" %>
    <ul class="flex">
      <li><%= link_to '質問一覧', questions_path(school_id: school.id) %></li>
      <li>＞</li>
      <li><%= link_to '質問投稿', "#", class: "link-underline" %></li>
    </ul>
  <% else %>
    <ul class="flex">
      <li><%= link_to '口コミ一覧', school_path(school) %></li>
      <li>＞</li>
      <li><%= link_to '質問一覧', questions_path(school_id: school.id) %></li>
      <li>＞</li>
      <li><%= link_to '質問投稿', "#", class: "link-underline" %></li>
    </ul>
  <% end %>
</div>

app/views/questions/_question_new_question_box.html.erb
<div class="review-and-question-box">
  <div class="review-and-question-box-content">
    <h2>質問投稿</h2>
    <%= form_with model: question, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="review-and-question-content-border">
        <ul class="flex question-form-user">
          <li class="question-user-icon">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image.variant(resize: '40x40!'), class: "user-icon", alt: "ユーザーアイコン" %>
            <% else %>
              <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
            <% end %>
          </li>
          <li class="question-form-user-name"><%= current_user.name %></li>
        </ul>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="review-and-question-content-border">
        <ul class="flex question-form-school">
          <li class="review-and-question-label"><%= f.label :school_id, "スクール名" %><span class="badge">必須</span></li>
          <li class=""><%= f.collection_select(:school_id, School.all, :id, :name, include_blank: '選択してください') %></li>
        </ul>
      </div>
      <div class="review-and-question-content-border">
        <ul>
          <li class="review-and-question-label"><%= f.label :name, "質問タイトル" %><span class="badge">必須</span></li>
          <li><%= f.text_field :name, placeholder: "質問のタイトルを入力してください" %></li>
        </ul>
      </div>
      <div class="question-form-content">
        <ul>
          <li class="review-and-question-label"><%= f.label :content, "質問内容" %><span class="badge">必須</span></li>
          <li><%= f.text_area :content, placeholder: "質問を入力してください", class: "resize10" %></li>
        </ul>
      </div>
      <%= hidden_field_tag :school_id, school.id %>
      <div class="review-and-question-button">
        <%= f.submit '投稿する', class: "submit-button" %>
        <%= link_to "戻る", questions_path(school_id: school.id), class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_question_show_answer_box.html.erb
<ul class="question-box answer-box">
  <div class="flex">
    <li>
      <%= link_to user_path(answer.user) do %>
        <% if answer.user.image.attached? %>
          <%= image_tag answer.user.image.variant(resize: '35x35!'), class: "user-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      <% end %>
    </li>
    <li class="question-user-name"><%= link_to answer.user.name, user_path(answer.user) %></li>
  </div>
  <div id='<%= answer.id %>'>
    <li class="question-show-text auto-adjust answer-text"><%= simple_format(answer.content) %></li>
    <li class="question-time"><%= answer.created_at.to_s(:datetime_jp) %></li>
    <% if user_signed_in? && (current_user == answer.user) %>
      <div class="question-show-buttons">
        <%= link_to "/answers/#{answer.id}/edit", method: :get, remote: true, class: "question-show-edit-button button" do %>
          <i class="fa fa-pencil" aria-hidden="true"></i><span>編集する</span>
        <% end %>
        <%= link_to "削除する", answer_path(answer), method: :delete, data: {confirm: "回答を削除しますか？"}, class: "question-show-delete-button button" %>
      </div>
      <div class="question-show-hidden-point hidden-point-<%= answer.id %>"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></div>
      <div class="question-show-hidden-menu fade-out hidden-menu-<%= answer.id %>">
        <%= link_to "編集", "/answers/#{answer.id}/edit", method: :get, remote: true, class: "hover-underline" %>
        <%= link_to "削除", answer_path(answer), method: :delete, data: {confirm: "回答を削除しますか？"}, class: "hover-underline delete-button" %>
      </div>
    <% end %>
  </div>
</ul>

app/views/questions/_question_show_answer_textarea_box.html.erb
<div class="question-box answer-textarea-box">
  <%= form_with model: answer, url: answers_path, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :content, placeholder: "回答を入力してください", class: "resize10" %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :question_id, value: question.id %>
    <%= f.submit '回答する', class: "submit-button" %>
  <% end %>
</div>

app/views/questions/_question_show_question_box.html.erb
<ul class="question-box">
  <div class="flex">
    <li>
      <%= link_to user_path(question.user) do %>
        <% if question.user.image.attached? %>
          <%= image_tag question.user.image.variant(resize: '35x35!'), class: "user-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      <% end %>
    </li>
    <li class="question-user-name"><%= link_to question.user.name, user_path(question.user) %></li>
  </div>
  <li class="question-name"><%= question.name %></li>
  <li class="question-show-text auto-adjust"><%= simple_format(question.content) %></li>
  <li class="question-time"><%= question.created_at.to_s(:datetime_jp) %></li>
  <% if user_signed_in? && (current_user == question.user) %>
    <div class="question-show-buttons">
      <%= link_to edit_question_path(question, question_edit_params: params), class: "question-show-edit-button button" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i><span>編集する</span>
      <% end %>
      <%= link_to "削除する", question_path(question), method: :delete, data: {confirm: "質問を削除しますか？"}, class: "question-show-delete-button button" %>
    </div>
    <div class="question-show-hidden-point show-button" v-on:click="show = !show"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></div>
    <div class="question-show-hidden-menu hidden-menu" v-bind:class="{ 'fade-in': !show, 'fade-out': show }">
      <%= link_to "編集", edit_question_path(question, question_edit_params: params), class: "hover-underline" %>
      <%= link_to "削除", question_path(question), method: :delete, data: {confirm: "質問を削除しますか？"}, class: "hover-underline delete-button" %>
    </div>
  <% end %>
</ul>

app/views/questions/_question_show_solution_box.html.erb
<% if current_user == question.user %>
  <% if question.solution == 0 || question.solution == 1 %>
    <div class="question-box solution-box">
      <p>質問が解決したらボタンを押してください</p>
      <%= link_to "解決した", solved_path(question_id: question.id), class: "button" %>
    </div>
  <% else %>
    <div class="question-box solution-box">
      <p>追加の質問がある場合にはボタンを押してください</p>
      <%= link_to "解決済み", solved_path(question_id: question.id), class: "button unsolution" %>
    </div>
  <% end %>
<% end %>

app/views/questions/_question_show_solution_mark.html.erb
<% if question.solution == 0 %>
  <div class="solution solution-red">
    未回答
  </div>
<% elsif question.solution == 1 %>
  <div class="solution solution-orange">
    未解決
  </div>
<% else %>
  <div class="solution solution-green">
    解決済み
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= provide(:title, "質問編集") %>
<div class="question-edit background-blue">
  <%= render partial: 'question_edit_page_link', locals: { params: @params, question: @question } %>
  <%= render 'shared/flash_message' %>
  <%= render partial: 'question_edit_question_box', locals: { question: @question } %>
</div>

app/views/questions/index.html.erb
<%= provide(:title, "#{@school.name}の質問一覧") %>
<div class="question-index background-blue">
  <%= render partial: 'question_index_page_link', locals: { params: @params, school: @school } %>
  <%= render 'shared/flash_message' %>
  <%= render partial: 'shared/school_header', locals: { school: @school } %>
  <section class="question-index-field">
    <div class="question-index-button">
      <%= link_to '質問する', new_question_path(school_id: @school.id, question_new_params: @params), class: "button" %>
    </div>
    <div class="question-content">
      <div class="review-and-question-link">
        <%= link_to "口コミ一覧", school_path(@school) %>
        <%= link_to "質問一覧", "#" %>
      </div>
      <h2><%= @school.name %>の質問</h2>
      <div class="question-box-flex">
        <%= render partial: 'question_index_question_box', locals: { params: @params }, collection: @questions, as: :question %>
      </div>
      <%= link_to '質問する', new_question_path(school_id: @school.id, question_new_params: @params), class: "button" %>
    </div>
  </section>
</div>

app/views/questions/new.html.erb
<%= provide(:title, "質問投稿") %>
<div class="question-new background-blue">
  <%= render partial: 'question_new_page_link', locals: { params: @params, school: @school } %>
  <%= render 'shared/flash_message' %>
  <%= render partial: 'question_new_question_box', locals: { question: @question, school: @school } %>
</div>