config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'searches#home'
  get '/result', to: 'searches#result'
  get '/solved', to: 'questions#solved'
  post 'favorite_review/:id', to: 'favorite_reviews#create', as: 'create_favorite_review'
  delete 'favorite_review/:id', to: 'favorite_reviews#destroy', as: 'destroy_favorite_review'
  resources :users, only: [:show, :edit, :update]
  resources :schools
  resources :reviews
  resources :questions
  resources :answers, only: [:create, :edit, :update, :destroy]
  resources :user_schools, only: [:destroy]
  resources :notifications, only: [:index, :destroy]
  delete '/notification_all', to: 'notifications#destroy_all', as: 'destroy_all_notification'
end

app/models/notification.rb
class Notification < ApplicationRecord
  scope :order_new, -> { order(created_at: :desc) }
  belongs_to :review, optional: true
  belongs_to :answer, optional: true
  belongs_to :question, optional: true
  belongs_to :visiter, class_name: 'User', optional: true
  belongs_to :visited, class_name: 'User', optional: true

  def how_long_ago
    if (Time.current.to_s(:date_jp).to_i - created_at.to_s(:date_jp).to_i) == 0
      '今日'
    elsif (Time.current.to_s(:date_jp).to_i - created_at.to_s(:date_jp).to_i) >= 100
      '1ヶ月前'
    elsif (Time.current.to_s(:date_jp).to_i - created_at.to_s(:date_jp).to_i) >= 200
      created_at.to_s(:datetime_jp)
    else
      "#{(Time.current.to_s(:date_jp).to_i - created_at.to_s(:date_jp).to_i)}日前"
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :destroy, :destroy_all]

  def index
    @notifications = current_user.passive_notifications.
      paginate(page: params[:page]).per(30).order_new
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    if current_user?(@notification.visited)
      if @notification.destroy
        flash[:success] = "通知を削除しました"
        redirect_to notifications_path
      else
        flash.now[:failure] = "通知を削除できませんでした"
        render "index"
      end
    else
      flash[:failure] = "他のユーザーの通知は削除できません"
      redirect_to notifications_path
    end
  end

  def destroy_all
    @user = User.find(params[:user_id])
    if current_user?(@user)
      if current_user.passive_notifications.destroy_all
        flash[:success] = "通知を全て削除しました"
        redirect_to notifications_path
      else
        flash.now[:failure] = "通知を削除できませんでした"
        render "index"
      end
    else
      flash[:failure] = "他のユーザーの通知は削除できません"
      redirect_to notifications_path
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification_index_notification_box.html.erb
<div class="one-notification-box">
  <% if notification.action == "like" %>
    <div class="one-notification-box-flex">
      <%= link_to user_path(notification.visiter) do %>
        <% if notification.visiter.image.attached? %>
          <%= image_tag notification.visiter.image.variant(resize: '40x40!'), class: "user-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      <% end %>
      <div class="notification-title">
        <%= link_to notification.visiter.name, user_path(notification.visiter), class: "notification-link" %>が
        <%= link_to 'あなたの口コミ', review_path(notification.review), class: "notification-link" %>にいいねしました。
        <%= "(#{notification.how_long_ago})" %>
      </div>
      <%= link_to "削除", notification_path(notification), method: :delete, data: {confirm: "この通知を削除しますか？"}, class: "notification-like-delete" %>
    </div>
    <p class="notification-content"><%= notification.review.name %></p>
  <% elsif notification.action == "answer" %>
    <div class="one-notification-box-flex">
      <%= link_to user_path(notification.visiter) do %>
        <% if notification.visiter.image.attached? %>
          <%= image_tag notification.visiter.image.variant(resize: '40x40!'), class: "user-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      <% end %>
      <div class="notification-title">
        <%= link_to notification.visiter.name, user_path(notification.visiter), class: "notification-link" %>が
        <%= link_to 'あなたの質問', question_path(notification.question), class: "notification-link" %>に回答しました。
        <%= "(#{notification.how_long_ago})" %>
      </div>
      <%= link_to "削除", notification_path(notification), method: :delete, data: {confirm: "この通知を削除しますか？"}, class: "notification-answer-delete" %>
    </div>
    <%= simple_format(notification.answer.content.truncate(20), class: "notification-content") %>
  <% end %>
</div>

app/views/notifications/index.html.erb
<%= provide(:title, "通知一覧")%>
<%= render 'shared/flash_message' %>
<div class="notification-index">
  <div class="all-notification-box">
    <h2>通知</h2>
    <% if @notifications.exists? %>
      <%= link_to destroy_all_notification_path(user_id: @notifications.first.visited.id), method: :delete, data: {confirm: "通知を全て削除しますか？"}, class: "all-notifications-delete" do %>
        <i class="fa fa-trash" aria-hidden="true"></i>全削除
      <% end %>
      <div>
        <%= render partial: 'notifications/notification_index_notification_box', collection: @notifications, as: :notification %>
      </div>
    <% else %>
      <p class="not-notification">通知はありません</p>
    <% end %>
    <% unless (will_paginate @notifications).nil? %>
      <div class="paginate">
        <%= will_paginate @notifications, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
      </div>
    <% end %>
  </div>
</div>