config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'searches#home'
  get '/result', to: 'searches#result'
  get '/solved', to: 'questions#solved'
  post 'favorite_review/:id', to: 'favorite_reviews#create', as: 'create_favorite_review'
  delete 'favorite_review/:id', to: 'favorite_reviews#destroy', as: 'destroy_favorite_review'
  resources :users, only: [:show, :edit, :update]
  resources :schools
  resources :reviews
  resources :questions
  resources :answers, only: [:create, :edit, :update, :destroy]
  resources :user_schools, only: [:destroy]
  resources :notifications, only: [:index, :destroy]
  delete '/notification_all', to: 'notifications#destroy_all', as: 'destroy_all_notification'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p class="alert alert-danger">
      <%= object.errors.count %>件のエラー
    </p>
    <ul class="alert">
      <% object.errors.full_messages.each.with_index(1) do |msg, i| %>
        <li><%= "#{i}. #{msg}" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 2022 プロコミ.</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-left">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', class: "logo" %>
    <% end %>
    <%= search_form_for @q, url: result_path do |f| %>
      <%= f.search_field :name_cont, placeholder: 'スクール名で検索' %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <ul class="header-right header-pc">
      <li><%= link_to "HOME", root_path %></li>
      <li><%= link_to "検索", result_path %></li>
      <li class="header-school">
        <%= link_to "スクール" %>
        <ul class="header-dropdown">
          <li class="header-dropdown-list"><%= link_to "スクール一覧", schools_path %></li>
          <li class="header-dropdown-list"><%= link_to "スクール追加", new_school_path %></li>
        </ul>
      </li>
      <li><%= link_to "口コミ投稿", new_review_path %></li>
      <li class="header-icon">
        <div>
          <% if current_user.image.attached? %>
            <%= link_to do %>
              <%= image_tag current_user.image.variant(resize: '100x100!'), class: "user-icon" %>
            <% end %>
          <% else %>
            <%= link_to do %>
              <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
            <% end %>
          <% end %>
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle unchecked-notification-sign" aria-hidden="true"></i>
          <% end %>
        </div>
        <ul class="header-dropdown">
          <li class="header-dropdown-list">
            <%= link_to "通知", notifications_path %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle unchecked-notification-sign" aria-hidden="true"></i>
            <% end %>
          </li>
          <li class="header-dropdown-list"><%= link_to "プロフィール", user_path(current_user) %></li>
          <li class="header-dropdown-list"><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
          <li class="header-dropdown-list"><%= link_to "アカウント　情報編集", edit_user_registration_path %></li>
          <li class="header-dropdown-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    </ul>
  <% else %>
    <ul class="header-right header-pc">
      <li><%= link_to "HOME", root_path %></li>
      <li class="header-school">
        <%= link_to "スクール" %>
        <ul class="header-dropdown">
          <li class="header-dropdown-list"><%= link_to "スクール検索", result_path %></li>
          <li class="header-dropdown-list"><%= link_to "スクール一覧", schools_path %></li>
        </ul>
      </li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li class="header-icon header-icon-guest">
        <%= link_to new_user_session_path do %>
          <%= image_tag src='70b3dd52350bf605f1bb4078ef79c9b9.png', class: "user-icon-default", alt: "ユーザーアイコン" %>
        <% end %>
      </li>
    </ul>
  <% end %>
  <div class="header-right header-tab-sp">
    <i id="menu-button" class="fa fa-bars header-hidden-menu-close-open-button" aria-hidden="true"></i>
    <% if user_signed_in? && unchecked_notifications.any? %>
      <i class="fa fa-circle unchecked-notification-sign" aria-hidden="true"></i>
    <% end %>
  </div>
</header>

app/views/shared/_header_hidden.html.erb
<div class="header-hidden-menu-background weak-hidden"></div>
<% if user_signed_in? %>
  <ul class="header-hidden-menu">
    <li class="header-hidden-menu-close"><i class="fa fa-times header-hidden-menu-close-open-button" aria-hidden="true"></i></li>
    <li class="header-hidden-menu-list">
      <%= link_to root_path do %>
        HOME<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to result_path do %>
        検索<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-school">
      <div class="header-dropdown-label header-hidden-menu-list">
        <%= link_to do %>
          スクール<i class="fa fa-chevron-right" aria-hidden="true"></i>
        <% end %>
      </div>
      <ul class="header-dropdown">
        <li class="header-dropdown-list">
          <%= link_to schools_path do %>
            スクール一覧<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="header-dropdown-list">
          <%= link_to new_school_path do %>
            スクール追加<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to new_review_path do %>
        口コミ投稿<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to notifications_path do %>
        通知<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
      <% if unchecked_notifications.any? %>
        <i class="fa fa-circle unchecked-notification-sign" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-user">
      <div class="header-dropdown-label header-hidden-menu-list">
        <%= link_to do %>
          設定<i class="fa fa-chevron-right" aria-hidden="true"></i>
        <% end %>
      </div>
      <ul class="header-dropdown">
        <li class="header-dropdown-list">
          <%= link_to user_path(current_user) do %>
            プロフィール<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="header-dropdown-list">
          <%= link_to edit_user_path(current_user) do %>
            プロフィール編集<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="header-dropdown-list">
          <%= link_to edit_user_registration_path do %>
            アカウント情報編集<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to destroy_user_session_path, method: :delete do %>
        ログアウト<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
  </ul>
<% else %>
  <ul class="header-hidden-menu">
    <li class="header-hidden-menu-close"><i class="fa fa-times header-hidden-menu-close-open-button" aria-hidden="true"></i></li>
    <li class="header-hidden-menu-list">
      <%= link_to root_path do %>
        HOME<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-school">
      <div class="header-dropdown-label header-hidden-menu-list">
        <%= link_to do %>
          スクール<i class="fa fa-chevron-right" aria-hidden="true"></i>
        <% end %>
      </div>
      <ul class="header-dropdown">
        <li class="header-dropdown-list">
          <%= link_to result_path do %>
            スクール検索<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="header-dropdown-list">
          <%= link_to schools_path do %>
            スクール一覧<i class="fa fa-chevron-right" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to new_user_session_path do %>
        ログイン<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
    <li class="header-hidden-menu-list">
      <%= link_to new_user_registration_path do %>
        新規登録<i class="fa fa-chevron-right" aria-hidden="true"></i>
      <% end %>
    </li>
  </ul>
<% end %>

app/views/shared/_school_header.html.erb
<section class="school-header">
  <div class="school-header-content flex">
    <div class="school-image-box">
      <% if school.image.attached? %>
        <%= image_tag school.image.variant(resize: '300x200!'), class: "school-icon", alt: "スクールアイコン" %>
      <% else %>
        <%= image_tag src='default-school.jpg', class: "school-icon-default", alt: "スクールアイコン" %>
      <% end %>
    </div>
    <div class="school-name-explanation-box">
      <p class="school-header-name"><%= school.name %></p>
      <div class="school-header-explanation">
        <%= simple_format(school.explanation) %>
      </div>
    </div>
    <div class="school-evaluation-box">
      <ul>
        <div class="responsive-flex">
          <% unless school.review_ave_score.nil? %>
            <li id='school-header-star-<%= school.id %>' class="stars"></li>
            <li class="ave"><%= school.review_ave_score %></li>
          <% end %>
        </div>
        <% if school.review_count.nil? %>
          <li>口コミ: 0件</li>
          <%= link_to "口コミを書く", new_review_path, class: "button blue" %>
        <% else %>
          <li><%= "口コミ: #{ school.review_count }件" %></li>
        <% end %>
        <% unless school.site_address.blank? %>
          <li>
            <%= link_to "公式サイトへ", "#{school.site_address}", target: :_blank, rel: "noopener noreferrer", class: "button" %>
          </li>
        <% end %>
      </ul>
      <%= render partial: 'shared/school_header_star', locals: { school: school } %>
    </div>
  </div>
</section>

app/views/shared/_school_header_star.html.erb
<script>
  window.addEventListener("turbolinks:load", function(){
    $('#school-header-star-<%= school.id %>').empty();
    $('#school-header-star-<%= school.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half      : true,
      readOnly: true,
      score: '<%= school.review_ave_score %>'
    });
  });
</script>

app/views/shared/_top_btn.html.erb
<span id="top-btn">
  <a href="#">
    <%= image_tag asset_path('top_btn.png'), class: 'top-btn' %>
  </a>
</span>