config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'searches#home'
  get '/result', to: 'searches#result'
  get '/solved', to: 'questions#solved'
  post 'favorite_review/:id', to: 'favorite_reviews#create', as: 'create_favorite_review'
  delete 'favorite_review/:id', to: 'favorite_reviews#destroy', as: 'destroy_favorite_review'
  resources :users, only: [:show, :edit, :update]
  resources :schools
  resources :reviews
  resources :questions
  resources :answers, only: [:create, :edit, :update, :destroy]
  resources :user_schools, only: [:destroy]
  resources :notifications, only: [:index, :destroy]
  delete '/notification_all', to: 'notifications#destroy_all', as: 'destroy_all_notification'
end

app/models/school.rb
class School < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :language
  belongs_to :cost
  belongs_to :period
  has_one_attached :image

  has_many :user_schools, dependent: :destroy
  has_many :users, through: :user_schools
  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :explanation, presence: true, length: { in: 1..300 }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]

  def index
    @params = params[:signal]
    if @params == "review-count"
      @schools = School.paginate(page: params[:page]).order(review_count: :desc,
                                                            review_ave_score: :desc)
    elsif @params == "review-score"
      @schools = School.paginate(page: params[:page]).order(review_ave_score: :desc,
                                                            review_count: :desc)
    elsif @params == "new"
      @schools = School.paginate(page: params[:page]).order(id: :desc)
    else
      @schools = School.paginate(page: params[:page])
    end
  end

  def show
    @params = params[:school_show_params]
    @school = School.find(params[:id])
    @reviews = Review.where(school_id: @school.id).order(created_at: :desc)
  end

  def new
    @params = params[:school_new_params]
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      flash[:success] = "スクールを追加しました"
      redirect_to schools_path(signal: "new")
    else
      flash.now[:failure] = "スクールを追加できませんでした"
      render "new"
    end
  end

  def edit
    @params = params[:school_edit_params]
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    if @school.update(school_params)
      flash[:success] = "スクール情報を変更しました"
      redirect_to school_path(@school)
    else
      flash.now[:failure] = "スクール情報を変更できませんでした"
      render "edit"
    end
  end

  private

  def school_params
    params.require(:school).
      permit(:name, :style, :support, :guarantee, :explanation,
            :language_id, :prefecture_id, :cost_id, :period_id,
            :review_ave_score, :review_count, :image, :site_address)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_school_edit_school_form.html.erb
<%= form_with model: school, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="image-box">
    <% if school.image.attached? %>
      <%= image_tag school.image.variant(resize: '300x200!'), class: "school-icon", alt: "スクールアイコン" %>
    <% else %>
      <%= image_tag src='default-school.jpg', class: "school-icon-default", alt: "スクールアイコン" %>
    <% end %>
  </div>
  <div class="flex">
    <div class="school-form-flex-item">
      <ul class="school-form-flex-item-left span-badge">
        <li><%= f.label :name, "スクール名", class: "school-form-label" %><span class="badge">必須</span></li>
        <li><%= f.text_field :name, placeholder: "スクール名を入力", class: "school-name-input" %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :language_id, "学習言語", class: "school-form-label" %></li>
        <li><%= f.collection_select(:language_id, Language.all, :id, :name, {}) %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :cost_id, "費用", class: "school-form-label"  %></li>
        <li><%= f.collection_select(:cost_id, Cost.all, :id, :range, {}) %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :period_id, "学習期間", class: "school-form-label" %></li>
        <li><%= f.collection_select(:period_id, Period.all, :id, :range, {}) %></li>
      </ul>
    </div>
    <div class="school-form-flex-item">
      <ul class="school-form-flex-item-right">
        <li><%= f.label :sytle, "学習形態", class: "school-form-label" %></li>
        <li><%= f.select :style, ['通学', 'オンライン', '通学とオンライン'], { include_blank: '---'} %></li>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :prefecture_id, "都道府県", class: "school-form-label" %></li>
        <li><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}) %>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :support, "転職支援", class: "school-form-label" %></li>
        <li><%= f.select :support, ['あり', 'なし'], { include_blank: '---'} %></li>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :guarantee, "転職保証", class: "school-form-label" %></li>
        <li><%= f.select :guarantee, ['あり', 'なし'], { include_blank: '---'} %>
      </ul>
    </div>
  </div>
  <ul class="school-form-image flex">
    <li><%= f.label :image, "スクール画像", class: "school-form-label" %></li>
    <li><%= f.file_field :image %></li>
  </ul>
  <ul class="school-form-url flex">
    <li><%= f.label :site_address, "公式サイトのURL", class: "school-form-label" %></li>
    <li><%= f.text_area :site_address, class: "resize2" %></li>
  </ul>
  <ul class="school-form-explanation">
    <li>
      <%= f.label :explanation, "特徴", class: "school-form-label" %>
      <span class="badge">必須</span>
    </li>
    <li><%= f.text_area :explanation, placeholder: "特徴を入力してください", class: "resize10" %>
  </ul>
  <%= f.submit '変更する', class: "submit-button" %>
<% end %>

app/views/schools/_school_index_nav.html.erb
<div class="flex">
  <div class="display-results"><%= schools.count %>件中
    <% if (params[:page].nil?) || (params[:page] == "1")  %>
      <%= 1 %>
    <% else %>
      <%= (params[:page].to_i - 1) * 30 + 1 %>
    <% end %>
    -
    <% if (params[:page].nil?) || (params[:page] == "1")  %>
      <% if schools.count.to_i < 30 %>
        <%= schools.count %>件表示
      <% else %>
        30件表示
      <% end %>
    <% elsif schools.count.to_i < (params[:page].to_i * 30) %>
      <%= schools.count %>件表示
    <% else %>
      <%= (params[:page]).to_i * 30 %>件表示
    <% end %>
  </div>
  <div class="sort">
    <%= form_with url: schools_path, method: :get, id: "form1", local: true do |f| %>
      <%= select_tag :signal, options_for_select([
                              ['口コミ評価順', 'review-score'],
                              ['口コミ数順', 'review-count'],
                              ['新しい順', 'new'],
                              ['古い順']
                            ]), include_blank: "並び替え", id: 'select' %>
    <% end %>
  </div>
</div>

app/views/schools/_school_index_page_link.html.erb
<div class="page-link">
  <ul>
    <li><%= link_to 'スクール一覧', "#", class: "link-underline" %></li>
  </ul>
</div>

app/views/schools/_school_index_schools_box.html.erb
<div class="schools-box">
  <% schools.each do |school| %>
    <ul class="flex one-school-box">
      <li class="school-image-box flex">
        <% if school.image.attached? %>
          <%= link_to (image_tag school.image.variant(resize: '300x200!'), class: "school-icon", alt: "スクールアイコン"), school_path(school, school_show_params: "school_index") %>
        <% else %>
          <%= link_to (image_tag src='default-school.jpg', class: "school-icon-default", alt: "スクールアイコン"), school_path(school, school_show_params: "school_index") %>
        <% end %>
      </li>
      <div class="school-name-explanation-box">
        <li>
          <%= link_to school.name, school_path(school, school_show_params: "school_index"), class: "hover-underline"  %>
        </li>
        <li><%= simple_format(school.explanation.truncate(40)) %></li>
      </div>
      <li class="school-evaluation-box flex">
        <ul>
          <div class="responsive-flex">
            <% unless school.review_ave_score.nil? %>
              <li id='school-index-star-<%= school.id %>' class="stars"></li>
              <li class="ave"><%= school.review_ave_score %></li>
            <% end %>
          </div>
          <% if school.review_count.nil? %>
            <li>
              <%= link_to "口コミ: 0件", new_review_path, class: "hover-underline" %>
            </li>
          <% else %>
            <li>
              <%= link_to "口コミ: #{ school.review_count }件", school_path(school, school_show_params: "school_index"), class: "hover-underline" %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
    <%= render partial: 'school_index_star', locals: { school: school } %>
  <% end %>
</div>

app/views/schools/_school_index_star.html.erb
<script>
  window.addEventListener("turbolinks:load", function(){
    $('#school-index-star-<%= school.id %>').empty();
    $('#school-index-star-<%= school.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half      : true,
      readOnly: true,
      score: '<%= school.review_ave_score %>'
    });
  });
</script>

app/views/schools/_school_new_page_link.html.erb
<div class="page-link">
  <% if params == "school_index" %>
    <ul class="flex">
      <li><%= link_to 'スクール一覧', schools_path %></li>
      <li>＞</li>
      <li><%= link_to 'スクール追加', "#", class: "link-underline" %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to 'スクール追加', "#", class: "link-underline" %></li>
    </ul>
  <% end %>
</div>

app/views/schools/_school_new_school_form.html.erb
<%= form_with model: school, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="flex">
    <div class="school-form-flex-item">
      <ul class="school-form-flex-item-left span-badge">
        <li><%= f.label :name, "スクール名", class: "school-form-label" %><span class="badge">必須</span></li>
        <li><%= f.text_field :name, placeholder: "スクール名を入力", class: "school-name-input" %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :language_id, "学習言語", class: "school-form-label" %></li>
        <li><%= f.collection_select(:language_id, Language.all, :id, :name, {}) %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :cost_id, "費用", class: "school-form-label"  %></li>
        <li><%= f.collection_select(:cost_id, Cost.all, :id, :range, {}) %></li>
      </ul>
      <ul class="school-form-flex-item-left">
        <li><%= f.label :period_id, "学習期間", class: "school-form-label" %></li>
        <li><%= f.collection_select(:period_id, Period.all, :id, :range, {}) %></li>
      </ul>
    </div>
    <div class="school-form-flex-item">
      <ul class="school-form-flex-item-right">
        <li><%= f.label :sytle, "学習形態", class: "school-form-label" %></li>
        <li><%= f.select :style, ['通学', 'オンライン', '通学とオンライン'], { include_blank: '---'} %></li>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :prefecture_id, "都道府県", class: "school-form-label" %></li>
        <li><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}) %></li>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :support, "転職支援", class: "school-form-label" %></li>
        <li><%= f.select :support, ['あり', 'なし'], { include_blank: '---'} %></li>
      </ul>
      <ul class="school-form-flex-item-right">
        <li><%= f.label :guarantee, "転職保証", class: "school-form-label" %></li>
        <li><%= f.select :guarantee, ['あり', 'なし'], { include_blank: '---'} %></li>
      </ul>
    </div>
  </div>
  <ul class="school-form-image flex">
    <li><%= f.label :image, "スクール画像", class: "school-form-label" %></li>
    <li><%= f.file_field :image %></li>
  </ul>
  <ul class="school-form-url flex">
    <li><%= f.label :site_address, "公式サイトのURL", class: "school-form-label" %></li>
    <li><%= f.text_area :site_address, class: "resize2" %></li>
  </ul>
  <ul class="school-form-explanation">
    <li><%= f.label :explanation, "特徴", class: "school-form-label" %><span class="badge">必須</span></li>
    <li><%= f.text_area :explanation, placeholder: "特徴を入力してください", class: "resize10" %></li>
  </ul>
  <%= f.submit '追加する', class: "submit-button" %>
<% end %>

app/views/schools/_school_show_favorite_review.html.erb
<% if user_signed_in? %>
  <% if current_user.liked_by?(review.id, current_user.id) %>
    <%= link_to destroy_favorite_review_path(review), method: :DELETE, remote: true do %>
      <i class="fa fa-heart on-favorite-review" aria-hidden="true"></i>
    <% end %>
    <%= review.favorite_reviews.count %>
  <% else %>
    <%= link_to create_favorite_review_path(review), method: :POST, remote: true do %>
      <i class="fa fa-heart off-favorite-review" aria-hidden="true"></i>
    <% end %>
    <%= review.favorite_reviews.count %>
  <% end %>
<% else %>
  <%= link_to create_favorite_review_path(review), method: :POST, remote: true do %>
    <i class="fa fa-heart off-favorite-review" aria-hidden="true"></i>
  <% end %>
  <%= review.favorite_reviews.count %>
<% end %>

app/views/schools/_school_show_review.html.erb
<div class="school-show-review">
  <h2 id ="review"><%= school.name %>の口コミ</h2>
  <div class="flex">
    <% reviews.each do |review| %>
      <div class="school-show-review-box schools-box">
        <%= link_to review_path(review, review_show_params: params) do %>
          <div class="school-show-review-name hover-underline">
            <i class="fa fa-comments-o" aria-hidden="true"></i>
            <%= review.name %>
          </div>
          <% unless review.average_star.nil? %>
            <ul>
              <li id='school-show-review-star-<%= review.id %>'></li>
              <li class="school-show-review-ave ave"><%= review.average_star %></li>
            </ul>
          <% end %>
          <div class="school-show-review-thought">
            <%= simple_format(review.thought.truncate(40)) %>
          </div>
          <%= render partial: 'school_show_review_star', locals: { review: review } %>
        <% end %>
        <div id="favorite_review_<%= review.id %>" class="favorite-review">
          <%= render 'school_show_favorite_review', review: review %>
        </div>
        <p class="school-show-review-time"><%= review.created_at.to_s(:datetime_jp) %></p>
      </div>
    <% end %>
  </div>
  <%= link_to "口コミを投稿する", new_review_path(review_new_params: params || "only_school_show", school_id: school.id), class: "button" %>
</div>

app/views/schools/_school_show_review_star.html.erb
<script>
  window.addEventListener("turbolinks:load", function(){
    $('#school-show-review-star-<%= review.id %>').empty();
    $('#school-show-review-star-<%= review.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half      : true,
      readOnly: true,
      score: '<%= ave_star(review) %>'
    });
  });
</script>

app/views/schools/_school_show_school_box.html.erb
<div class="school-show-school-box schools-box">
  <table>
    <tbody>
      <tr>
        <th><i class="fa fa-pencil" aria-hidden="true"></i>学習言語</th>
        <td><%= school.language.name %></td>
      </tr>
      <tr>
        <th><i class="fa fa-money" aria-hidden="true"></i>費用</th>
        <td><%= school.cost.range %></td>
      </tr>
      <tr>
        <th><i class="fa fa-calendar" aria-hidden="true"></i>学習期間</th>
        <td><%= school.period.range %></td>
      </tr>
      <tr>
        <th><i class="fa fa-television" aria-hidden="true"></i>学習形態</th>
        <td>
          <% if school.style.blank? %>
            ---
          <% else %>
            <%= school.style %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><i class="fa fa-map-marker" aria-hidden="true"></i>都道府県</th>
        <td><%= school.prefecture.name %></td>
      </tr>
      <tr>
        <th><i class="fa fa-user-o" aria-hidden="true"></i>転職支援</th>
        <td>
          <% if school.support.blank? %>
            ---
          <% else %>
            <%= school.support %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><i class="fa fa-handshake-o" aria-hidden="true"></i>転職保証</th>
        <td>
          <% if school.guarantee.blank? %>
            ---
          <% else %>
            <%= school.guarantee %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <% unless school.site_address.blank? %>
    <%= link_to "公式サイトへ", "#{school.site_address}", target: :_blank, rel: "noopener noreferrer", class: "button" %>
  <% end %>
</div>

app/views/schools/_school_show_school_detail.html.erb
<section class="school-detail">
  <div class="review-and-question-link">
    <%= link_to "口コミ一覧", { anchor: "review" } %>
    <%= link_to "質問一覧", questions_path(school_id: school.id, question_index_params: params) %>
  </div>
  <h2><%= school.name %>の情報</h2>
  <%= render partial: 'school_show_school_box', locals: { school: school } %>
  <%= link_to "#{school.name}の情報を変更する", edit_school_path(school, school_edit_params: params), class: "school-show-edit-link" %>
  <%= render partial: 'school_show_review', locals: { school: school, reviews: reviews, params: params } %>
</section>

app/views/schools/index.html.erb
<%= provide(:title, "プログラミングスクール一覧")%>
<div class="background-blue">
  <%= render 'school_index_page_link' %>
  <%= render 'shared/flash_message' %>
  <div class="school-index">
    <%= link_to "スクール追加", new_school_path(school_new_params: "school_index"), class: "button" %>
    <div class="school-index-content">
      <%= render partial: 'school_index_nav', locals: { schools: @schools } %>
      <%= render partial: 'school_index_schools_box', locals: { schools: @schools } %>
      <% unless (will_paginate @schools).nil? %>
        <div class="paginate">
          <%= will_paginate @schools, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
        </div>
      <% end %>
      <%= link_to "プログラミングスクールを追加する", new_school_path(school_new_params: "school_index"), class: "button" %>
    </div>
  </div>
</div>
<%= render 'school_index_select_change' %>

app/views/schools/new.html.erb
<%= provide(:title, "プログラミングスクール新規追加") %>
<div class="school-new">
  <%= render partial: 'school_new_page_link', locals: { params: @params } %>
  <%= render 'shared/flash_message' %>
  <div class="school-search-box">
    <h2>プログラミングスクールの追加</h2>
    <%= render partial: 'school_new_school_form', locals: { school: @school } %>
  </div>
</div>